### ISSUE TITLE
Design new user interface for V2

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#13]
<a href="https://github.com/pirog"><img src="https://avatars.githubusercontent.com/u/713424?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pirog](https://github.com/pirog)**
_Friday Aug 08, 2014 at 03:30 GMT_
_Originally opened as https://github.com/kalabox/kalabox-installer/issues/19_

----

Start from https://github.com/kalamuna/kalaboxv1/issues/51

**Comment by madeofpeople** [comment]
"Add a site" changes: 
A big listing of different 'apps' (configurations/stack combos) eg. drupal (with 7,8, panopoly etc being subsequent options). Cloud platofrms (pantheon and acquia) are part of this list.
