### ISSUE TITLE
Chromebook/ChromeOS support?

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#18]
<a href="https://github.com/pirog"><img src="https://avatars.githubusercontent.com/u/713424?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pirog](https://github.com/pirog)**
_Friday Aug 08, 2014 at 03:17 GMT_
_Originally opened as https://github.com/kalabox/kalabox-installer/issues/2_

----

Chromebook is an intriguing possible platform to support given its low cost and likely usage in primary education and trainings. We need to discuss the feasibility of kalabox here. This discussion from the docker peeps is a good starting point
https://groups.google.com/forum/#!topic/docker-user/99vtMOLpuZY

The two obvious areas of concern are:
1. Does ChromeOS support VirtualBox and/or Docker (Linux kernel 3.8+)
2. Can we package and easily deploy a node-webkit app for ChromeOS? Do all chrome apps need to be on the internet/cloud or can they be stored locally and run in a browser?

**Comment by jpw1116** [comment]
Interesting timing: last week, it was revealed that kernels 3.14 and 3.18 will supposedly support Docker on Chromebooks. I think through crouton. But only newer c-books seem to feature kernels > 3.10.

**Comment by pirog** [comment]
oh very intersesting! 

still keeping this issue around but i am moving a bunch of stuff around to help us get better organized and efficient processing the issues
