### ISSUE TITLE
BUG: "kbox pressflow7 start" error when starting hipache

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-issues#221]
When running "kbox pressflow7 start" (after successfully running "kbox pressflow7 install") I'm getting this error:

```
/Users/alec/workspace/kalabox/plugins/hipache/index.js:25
          if (data && data.NetworkSettings.Ports[proxy.port]) {
                                                ^
TypeError: Cannot read property '80/tcp' of null
    at /Users/alec/workspace/kalabox/plugins/hipache/index.js:25:49
    at /Users/alec/workspace/kalabox/node_modules/dockerode/lib/container.js:46:7
    at Modem.buildPayload (/Users/alec/workspace/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:215:7)
    at IncomingMessage.<anonymous> (/Users/alec/workspace/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:178:14)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
```

**Comment by pirog** [comment]
im actually getting this error as well.... ON WINDOWS!!!!

must have introduced a regression

**Comment by pirog** [comment]
I can confirm this bug on OSX as well

**Comment by pirog** [comment]
If you uninstall and reinstall this should work now

**Comment by pirog** [comment]
So I actually broke this! Should be able to pull the latest pressflow7 app
and give it a go

On Tuesday, February 10, 2015, reynoldsalec <notifications@github.com>
wrote:

> When running "kbox pressflow7 start" (after successfully running "kbox
> pressflow7 install") I'm getting this error:
>
> /Users/alec/workspace/kalabox/plugins/hipache/index.js:25
>           if (data && data.NetworkSettings.Ports[proxy.port]) {
>                                                 ^
> TypeError: Cannot read property '80/tcp' of null
>     at /Users/alec/workspace/kalabox/plugins/hipache/index.js:25:49
>     at /Users/alec/workspace/kalabox/node_modules/dockerode/lib/container.js:46:7
>     at Modem.buildPayload (/Users/alec/workspace/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:215:7)
>     at IncomingMessage.<anonymous> (/Users/alec/workspace/kalabox/node_modules/dockerode/node_modules/docker-modem/lib/modem.js:178:14)
>     at IncomingMessage.EventEmitter.emit (events.js:117:20)
>     at _stream_readable.js:919:16
>     at process._tickCallback (node.js:419:13)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/221>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by reynoldsalec** [comment]
Cool, confirmed this works for me too.

**Comment by pirog** [comment]
very nice!
