### ISSUE TITLE
BUG/FEATURE: Disk space

### ISSUE THREAD

**Issue by soniktrooth** [kalabox/kalabox-issues#226]
```
TEP [8] -- Checking disk free space....
 --- 29461 MB free of the required 30000 MB
 *** Not enough disk space for install! ***
```

I was a little shocked at first that Kalabox needed 30gb of free space to install but after talking to @pirog I understand that the VM needs to reserve disk space for itself.

This seems a little problematic to me in this day of still relatively small SSDs. I have a rMBP with 256gb SSD and have to juggle my space a lot but there's a lot of people out there using MacBook Airs are stuck with 128gb drives.

Obviously I know nothing about what you've had to do to achieve what you have and I'm sure you didn't choose the 30gb arbitrarily but for me it's a bit of a show stopper. If a colleage said to me "Check it this rad new Drupal thing/MAMP replacement/whatever I came across today" and when I looked it said 'Requires at least 30gb' I wouldn't have even bothered because of how little wiggle room I have on my SSD.

**Comment by pirog** [comment]
Actually it was a little arbitrary. Gotta start somewhere ;) 

Yeah so we use VBMK for the storage so it has some flex to it. What would be a tolerable size for you? 

The actual install takes less than 500MB but once you start adding sites it can grow quickly. Maybe cut the check to 1G or something and then produce a warning if you don't have like 10Gs free or something?

**Comment by soniktrooth** [comment]
I think that sounds reasonable.

**Comment by pirog** [comment]
When I get back to the office I'll push a branch for you to try out for
this then!

On Thursday, February 12, 2015, Josh <notifications@github.com> wrote:

> I think that sounds reasonable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/226#issuecomment-74146936>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
In a way it's not really your responsibility for what people might do with Kalabox. When I install Transmission it doesn't tell me "Illegally downloaded movies can take up lots of space on your hard drive", but I understand that I need to manage what I do with it. A small time Drupal dev might make lots of 3 page sites for small businesses which isn't going to take up anywhere near the room that a university's site is. So I guess it's kind of a target audience concern as well.

**Comment by pirog** [comment]
Well the target audience is everybody.

If our responsibility is anything it's to make sure our product works on
people's machines. Available hard drive space is definitely part of that.

On Thursday, February 12, 2015, Josh <notifications@github.com> wrote:

> In a way it's not really your responsibility for what people might do with
> Kalabox. When I install Transmission it doesn't tell me "Illegally
> downloaded movies can take up lots of space on your hard drive", but I
> understand that I need to manage what I do with it. A small time Drupal dev
> might make lots of 3 page sites for small businesses which isn't going to
> take up anywhere near the room that a university's site is. So I guess it's
> kind of a target audience concern as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/226#issuecomment-74157521>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
Checking available disk space is def a pretty standard pre install check. I
think lowering the threshold to a reasonable level to ensure we can
actually install everything is def something we need to do.

Beyond that I think it would be fine to tell the user the recommended
amount of free space if they are under that threshold. That informs and
puts the ball in their court.

1G as the hard req and 10G as the recommended seems pretty reasonable and
of course we can change it as more feedback comes in.

On Thursday, February 12, 2015, Mike Pirog <mike@kalamuna.com> wrote:

> Well the target audience is everybody.
>
> If our responsibility is anything it's to make sure our product works on
> people's machines. Available hard drive space is definitely part of that.
>
> On Thursday, February 12, 2015, Josh <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> In a way it's not really your responsibility for what people might do
>> with Kalabox. When I install Transmission it doesn't tell me "Illegally
>> downloaded movies can take up lots of space on your hard drive", but I
>> understand that I need to manage what I do with it. A small time Drupal dev
>> might make lots of 3 page sites for small businesses which isn't going to
>> take up anywhere near the room that a university's site is. So I guess it's
>> kind of a target audience concern as well.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox-issues/issues/226#issuecomment-74157521>
>> .
>>
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
>

-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
@soniktrooth looks like this change stowed away into the latest master so it should only require 1GB now.

**Comment by soniktrooth** [comment]
Sweet, I will give it a spin
