### ISSUE TITLE
README not clear on many things. update all the readmes docs and wikis

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#241]
https://github.com/kalabox/kalabox

See Linux notes - Goes to Windowz Page

https://github.com/kalabox/kalabox-app-examples

kbox commands not correct with the way it was just changed the other day, start, install, etc all be incorrect now

**Comment by pirog** [comment]
Please write more detail actually describing your issue. This is also two issues.

**Comment by labboy0276** [comment]
I gave the links and where it is incorrect.  Ill just do a pull and handle it myself since I know where it is incorrect.

**Comment by pirog** [comment]
Pulls are better but def describe subsequent issues better as well.

"Command is incorrect" is not very helpful.

On Sunday, February 15, 2015, John Ouellet <notifications@github.com> wrote:

> I gave the links and where it is incorrect. Ill just do a pull and handle
> it myself since I know where it is incorrect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/241#issuecomment-74426201>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
I think the use of the word 'app' is confusing. I think I ignored the apps bit in the docs because I was expecting kbox to be serving websites for me, not apps...Does it have something to do with iPhone apps? Does it have something to do with hors d'oeuvres? The questions are endless.

Possibly just semantics but a point of confusion for someone coming from MAMPworld™ Here's how @pirog explained it to me in the Slacks:

> so "app" is just a loose concept since it may not be a website
> i guess "apps" is a superset of "websites" but each "app" has basically two components:
> 1.) the infrastructure that runs the app 
> 2.) the actual code/db/files/whatever that make your app your app
> the app examples will tell you how to set up a few of the first part of that
> the second part is something you will need to do manually for now but there are some loose directions > about how to do that in the app examples readmes as well

**Comment by pirog** [comment]
Open to different terms but feel like "app" is the generic term for these things right now although it is admittedly overused. 

Feel like maybe @reynoldsalec can add something here

**Comment by soniktrooth** [comment]
Apps example docs (https://github.com/kalabox/kalabox-app-examples) say:
```
Create ~/kalabox/kalabox.json and add the following to it.
```
but what they mean to say is: 
```
Create ~/.kalabox/kalabox.json and add the following to it. 
```

Note the missing full stop before the first kalabox. Without this the kalabox.json file is in the wrong place and won't get discovered and neither will the apps.
