### ISSUE TITLE
FEATURE: Simple git plugin and container

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#245]

**Comment by pirog** [comment]
this would run git and rysnc and things like that

**Comment by pirog** [comment]
@bcauldwell got a crappy problem here in that `syncthing` drops a `.stfolder` file into the synced folder and `git` cannot clone into a non-empty folder :(

**Comment by reynoldsalec** [comment]
@pirog did that issue with the .stfolder get resolved? Experienced that as well.

**Comment by pirog** [comment]
almost. 

@bcauldwell and i need to merge in a few branches to kalabox/kalabox but after that you should be able to use the git plugin to clone your code directly into the container and it will know how to handle the .stfolder file

**Comment by pirog** [comment]
working on the drush plugin now so should have git/drush as available commands you can run on your apps by end of day.

**Comment by pirog** [comment]
@reynoldsalec 
if you want you can give the `kalabox-plugin-git` a try now. pull the latest code from kalabox/kalabox/master and then see this to install the plugin in your app
https://github.com/kalabox/kalabox-plugin-git
