### ISSUE TITLE
Serious newb docs

### ISSUE THREAD

**Issue by soniktrooth** [kalabox/kalabox-issues#252]
So I ran 'kbox provision' which is as far as the docs take me but now I have no idea what's next. I'm happy to help write some docs for this if someone can step me through how to end up with kalabox serving me a site.

**Comment by pirog** [comment]
the docs are pretty long but at the end you'll see some stuff on how to set up your own apps and a link to kalabox-app-eamples. maybe that should be moved closer to the top

**Comment by pirog** [comment]
@soniktrooth going to close this in favor of #241 which will contain all 1337speak required to de-n00b the docs
