### ISSUE TITLE
BUG: Code directory and app subdirectories sometimes are not automatically created.

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#297]

**Comment by clickbox** [comment]
I found the directory it created in Users/Ezenwa/kalabox/code. I guess now I'm just wondering if I made the mistake of thinking that the "code" directory would be created inside the "kalabox" folder which is where it is installed. Or if I installed kalabox in a folder I should not have.

**Comment by pirog** [comment]
I just tested this out and deleted ~/kalabox/code... and installed and app and started it. The  code/appname directory was created for me during kbox start.
