### ISSUE TITLE
FEATURE: Include version in log file.

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#301]

**Comment by pirog** [comment]
ha! i was thinking that after looking at joshks log. OS would be a good
addition as well.

+100000

On Wed, Mar 4, 2015 at 10:46 AM, bcauldwell <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/301>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
