### ISSUE TITLE
Allow user to specify stignore patterns in app kalabox.json and turn sharing off

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#318]
OK

Not sure if this is due to a large file change and syncthing not keeping up, but here it is....

I had moved all the module folders into the best practices ways (contrib, custom, etc) many moons ago.  On kb1 & pantheon it sees this and worked fine.

When I spun out the sites on kb2 and then did my multidev switch, it didnt move any of the code around as it should have.  Which was odd, since it is ok in other environments.

I had to do a git reset --hard to an older commit then a git pull for it to win.

**Comment by pirog** [comment]
After you switch branches, what does the vm syncthing UI show?

On Monday, March 9, 2015, John Ouellet <notifications@github.com> wrote:

> OK
>
> Not sure if this is due to a large file change and syncthing not keeping
> up, but here it is....
>
> I had moved all the module folders into the best practices ways (contrib,
> custom, etc) many moons ago. On kb1 & pantheon it sees this and worked fine.
>
> When I spun out the sites on kb2 and then did my multidev switch, it didnt
> move any of the code around as it should have. Which was odd, since it is
> ok in other environments.
>
> I had to do a git reset --hard to an older commit then a git pull for it
> to win.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/318>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Nothing, it didnt change / re-sync.

I can give you access to the site if you want to test it

**Comment by pirog** [comment]
Which syncthing are you looking at?

On Monday, March 9, 2015, John Ouellet <notifications@github.com> wrote:

> Nothing, it didnt change / re-sync.
>
> I can give you access to the site if you want to test it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/318#issuecomment-77883240>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
I looked at both, also here is the other odd thing, the files didnt change in the /code dir either.

**Comment by pirog** [comment]
post the commands you are running and the directory you are running them in

On Mon, Mar 9, 2015 at 9:14 AM, John Ouellet <notifications@github.com>
wrote:

> I looked at both, also here is the other odd thing, the files didnt change
> in the /code dir either.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/318#issuecomment-77885350>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
OK i will in a little while, working on something else right meow

**Comment by labboy0276** [comment]
I gave you access  to kfp on pantheon so you can test this out as well

**Comment by pirog** [comment]
NOTE: rescan interval may impact this

**Comment by pirog** [comment]
K. I'll try this tomorrow when i have better internet as well.

**Comment by pirog** [comment]
hmmm. i was able to switch branches here and it seemed to work as expected. if you switch locally you have a wait a sec for the files to sync but after that it seems legit. 

Can you add the list of commands you are running so i can try to replicate what is happening over there.

**Comment by pirog** [comment]
We might want to consider a list of files syncthing should ignore. I think that would help here. 

We might want to consider OS specific files a la DS_STORE and things like the .git directory.
