### ISSUE TITLE
Upgrade syncthing?

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#326]

**Comment by bcauldwell** [comment]
New version of syncthing breaks the REST api. Update our code to fix the REST api break.

**Comment by pirog** [comment]
You will need to pull the syncthing branch and do an uninstall/reinstall.

you also will want to drop 

```json 
{
 "profile": "dev"
}
```

into your `~/.kalabox/kalabox.json`

**Comment by pirog** [comment]
Let's ping the borg on this and post the notes in here
