### ISSUE TITLE
Which command did you run without the VM on?

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#330]

**Comment by pirog** [comment]
kbox containers

On Fri, Mar 13, 2015 at 11:37 AM, bcauldwell <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/330>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
