### ISSUE TITLE
git/drush/rsync and db plugins do not seem to get loaded inside our app examples

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#352]

**Comment by pirog** [comment]
These plugins live in the node_modules folder of each app. Even after switching them to have the correct and new function signature they dont seem to be registered at all.

**Comment by bcauldwell** [comment]
Partially fixed, waiting for a slightly more elegant solution as well as a solution to npm install running on non 'app install' commands. Working on this now.
