### ISSUE TITLE
Command parsing on git commit "-m" flag requires space

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-issues#359]
Very small issue, but normally either

```git commit -m"some message."``` 
and 
```git commit -m "some message" ```
are both valid. With kbox git, you must put a space between the "-m" flag and the message content.

Assuming this is just more fine-tuning with the command parsing.

**Comment by pirog** [comment]
This should be fixed in pending 0.6.0 so closing for now
