### ISSUE TITLE
FEATURE: swap out shelljs

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#365]

**Comment by bcauldwell** [comment]
I cannot reproduce this error on my system. Will need to take a look at @mpirog's system to further troubleshoot.

**Comment by pirog** [comment]
Still getting this. Did a cursory check but couldn't find anything obvious. Very weird.

**Comment by bcauldwell** [comment]
Such a strange bug. It has something todo with var S = require('string'); in kalabox-services-kalabox/install.js, but only when node_modules/kalabox-services-kalabox/ is git cloned rather than npm installed. If you do a regular npm install the problem goes away.

**Comment by pirog** [comment]
So the steps to actually replicate this are:

1. Provision kalabox 0.5.0 as normal
2. Go into the node_modules/kalabox-* folders and run an `npm install`
3. run `kbox` from outside of the `node_modules` folder

**Comment by pirog** [comment]
Found out some more about this issue by happenstance

So even if you provision kbox normally. This shows up if you run `grunt unit`.

**Comment by pirog** [comment]
I think we should address this by removing our dep on shell.js
