### ISSUE TITLE
Running "kbox up" from inside uninstalled app causes error.

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-issues#369]
If I go inside of a non-initialized app and run "kbox up", I receive the following error:

```
/Users/alec/workspace/kalabox/lib/core/plugin.js:26
      throw new Error(context + ' ' + err);
            ^
Error: Unable to load plugin [kalabox-plugin-dbenv] TypeError: Object #<Object> has no method 'whenApp'
    at /Users/alec/workspace/kalabox/lib/core/plugin.js:26:13
    at Object.exports.override (/Users/alec/workspace/kalabox/lib/core/deps.js:166:3)
    at initPlugin (/Users/alec/workspace/kalabox/lib/core/plugin.js:20:8)
    at Object.exports.load (/Users/alec/workspace/kalabox/lib/core/plugin.js:109:12)
    at /Users/alec/workspace/kalabox/lib/app.js:122:32
    at Array.forEach (native)
    at /Users/alec/workspace/kalabox/lib/app.js:121:17
    at Object.exports.override (/Users/alec/workspace/kalabox/lib/core/deps.js:166:3)
    at Object.exports.loadPlugins (/Users/alec/workspace/kalabox/lib/app.js:120:13)
    at initWithApp (/Users/alec/workspace/kalabox/bin/kbox.js:60:12)
    at /Users/alec/workspace/kalabox/bin/kbox.js:275:9
    at /Users/alec/workspace/kalabox/bin/kbox.js:249:7
    at /Users/alec/workspace/kalabox/bin/kbox.js:214:19
    at Object.cb [as oncomplete] (fs.js:168:19)
```

Going outside of the app and running kbox up works as expected. "kbox up" works normally when run from inside apps that have already been installed.

**Comment by pirog** [comment]
Delete your node_modules folder inside the app and try again

On Monday, March 30, 2015, reynoldsalec <notifications@github.com> wrote:

> If I go inside of a non-initialized app and run "kbox up", I receive the
> following error:
>
> /Users/alec/workspace/kalabox/lib/core/plugin.js:26
>       throw new Error(context + ' ' + err);
>             ^
> Error: Unable to load plugin [kalabox-plugin-dbenv] TypeError: Object #<Object> has no method 'whenApp'
>     at /Users/alec/workspace/kalabox/lib/core/plugin.js:26:13
>     at Object.exports.override (/Users/alec/workspace/kalabox/lib/core/deps.js:166:3)
>     at initPlugin (/Users/alec/workspace/kalabox/lib/core/plugin.js:20:8)
>     at Object.exports.load (/Users/alec/workspace/kalabox/lib/core/plugin.js:109:12)
>     at /Users/alec/workspace/kalabox/lib/app.js:122:32
>     at Array.forEach (native)
>     at /Users/alec/workspace/kalabox/lib/app.js:121:17
>     at Object.exports.override (/Users/alec/workspace/kalabox/lib/core/deps.js:166:3)
>     at Object.exports.loadPlugins (/Users/alec/workspace/kalabox/lib/app.js:120:13)
>     at initWithApp (/Users/alec/workspace/kalabox/bin/kbox.js:60:12)
>     at /Users/alec/workspace/kalabox/bin/kbox.js:275:9
>     at /Users/alec/workspace/kalabox/bin/kbox.js:249:7
>     at /Users/alec/workspace/kalabox/bin/kbox.js:214:19
>     at Object.cb [as oncomplete] (fs.js:168:19)
>
> Going outside of the app and running kbox up works as expected. "kbox up"
> works normally when run from inside apps that have already been installed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/369>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by reynoldsalec** [comment]
Hmm, yes, I think I exploded something. I'm guessing I just stepped into a node dependency funk probably related to dev updates, so I'm going to close this out @pirog and snag you when you're in the office.

**Comment by pirog** [comment]
we exploded it by breaking the API again in 0.5.0.

On Mon, Mar 30, 2015 at 10:25 AM, reynoldsalec <notifications@github.com>
wrote:

> Hmm, yes, I think I exploded something. I'm guessing I just stepped into a
> node dependency funk probably related to dev updates, so I'm going to close
> this out @pirog <https://github.com/pirog> and snag you when you're in
> the office.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/369#issuecomment-87760537>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by reynoldsalec** [comment]
Ah, so that's probably a re-install for me, right?

**Comment by pirog** [comment]
https://github.com/kalabox/kalabox

see the "pre-install" section.

On Mon, Mar 30, 2015 at 10:28 AM, reynoldsalec <notifications@github.com>
wrote:

> Ah, so that's probably a re-install for me, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/369#issuecomment-87761537>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
