### ISSUE TITLE
FEATURE: simplify kbox.require

### ISSUE THREAD

**Issue by pirog** [kalabox/kalabox-issues#377]

**Comment by pirog** [comment]
You will likely want to branch from `jewel-soulsaver`

**Comment by pirog** [comment]
As part of this we might want to print a message to the user that they may need to run "npm install"  if a module is not found at line 218ish of require.js

**Comment by bcauldwell** [comment]
This is done, and I did a small amount of testing. Further testing will be needed before released as part of a full manual functional test.
