### ISSUE TITLE
Git plugin Failing now 

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#382]
I did a pull on kb2 and apps today.  I went to install a new app and this is happening now.  I can do a workaround by pasting the plugins from my other apps and it works ok.  Here is the error I am getting:

```
john@kalamuna:~/kalabox/apps/blog$ kbox install
npm WARN package.json kalabox-app-blog@0.0.0 No repository field.
kalabox-plugin-dbenv@0.5.1 node_modules/kalabox-plugin-dbenv

kalabox-plugin-rsync@0.5.2 node_modules/kalabox-plugin-rsync

kalabox-plugin-git@0.6.0 node_modules/kalabox-plugin-git

kalabox-plugin-drush@0.5.2 node_modules/kalabox-plugin-drush
└── lodash@2.4.1
error: kalabox-plugin-git -> Cannot call method 'add' of undefined kalabox-plugin-git -> Cannot call method 'add' of undefined
TypeError: Cannot call method 'add' of undefined
    at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-git/index.js:109:16
    at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
    at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
    at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
    at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-git/index.js:14:8)
    at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
    at /home/john/kb2/lib/require.js:349:39
    at /home/john/kb2/lib/require.js:229:7
    at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
    at /home/john/kb2/lib/require.js:212:7
    at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
    at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
    at requireModule (/home/john/kb2/lib/require.js:226:3)
    at requireInternal (/home/john/kb2/lib/require.js:278:3)
    at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
    at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)

/home/john/kb2/bin/kbox.js:124
    throw err;
          ^
kalabox-plugin-git -> Cannot call method 'add' of undefined
TypeError: Cannot call method 'add' of undefined
    at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-git/index.js:109:16
    at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
    at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
    at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
    at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-git/index.js:14:8)
    at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
    at /home/john/kb2/lib/require.js:349:39
    at /home/john/kb2/lib/require.js:229:7
    at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
    at /home/john/kb2/lib/require.js:212:7
    at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
    at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
    at requireModule (/home/john/kb2/lib/require.js:226:3)
    at requireInternal (/home/john/kb2/lib/require.js:278:3)
    at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
    at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)

```

**Comment by pirog** [comment]
Don't use the latest version of plugins. Use ~0.5.1

On Tuesday, April 7, 2015, John Ouellet <notifications@github.com> wrote:

> I did a pull on kb2 and apps today. I went to install a new app and this
> is happening now. I can do a workaround by pasting the plugins from my
> other apps and it works ok. Here is the error I am getting:
>
> john@kalamuna:~/kalabox/apps/blog$ kbox install
> error: kalabox-plugin-drush -> Cannot call method 'add' of undefined kalabox-plugin-drush -> Cannot call method 'add' of undefined
> TypeError: Cannot call method 'add' of undefined
>     at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:168:16
>     at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
>     at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
>     at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
>     at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:18:8)
>     at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
>     at /home/john/kb2/lib/require.js:349:39
>     at /home/john/kb2/lib/require.js:229:7
>     at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
>     at /home/john/kb2/lib/require.js:212:7
>     at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
>     at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
>     at requireModule (/home/john/kb2/lib/require.js:226:3)
>     at requireInternal (/home/john/kb2/lib/require.js:278:3)
>     at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
>     at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)
>
> /home/john/kb2/bin/kbox.js:116
>       throw err;
>             ^
> kalabox-plugin-drush -> Cannot call method 'add' of undefined
> TypeError: Cannot call method 'add' of undefined
>     at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:168:16
>     at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
>     at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
>     at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
>     at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:18:8)
>     at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
>     at /home/john/kb2/lib/require.js:349:39
>     at /home/john/kb2/lib/require.js:229:7
>     at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
>     at /home/john/kb2/lib/require.js:212:7
>     at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
>     at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
>     at requireModule (/home/john/kb2/lib/require.js:226:3)
>     at requireInternal (/home/john/kb2/lib/require.js:278:3)
>     at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
>     at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/382>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
There shouldn't be any recent code from kalabox either. Last merge to
master was like 10 days ago. Dev branches are not supported.

On Tuesday, April 7, 2015, Mike Pirog <mike@kalamuna.com> wrote:

> Don't use the latest version of plugins. Use ~0.5.1
>
> On Tuesday, April 7, 2015, John Ouellet <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I did a pull on kb2 and apps today. I went to install a new app and this
>> is happening now. I can do a workaround by pasting the plugins from my
>> other apps and it works ok. Here is the error I am getting:
>>
>> john@kalamuna:~/kalabox/apps/blog$ kbox install
>> error: kalabox-plugin-drush -> Cannot call method 'add' of undefined kalabox-plugin-drush -> Cannot call method 'add' of undefined
>> TypeError: Cannot call method 'add' of undefined
>>     at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:168:16
>>     at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
>>     at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
>>     at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
>>     at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:18:8)
>>     at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
>>     at /home/john/kb2/lib/require.js:349:39
>>     at /home/john/kb2/lib/require.js:229:7
>>     at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
>>     at /home/john/kb2/lib/require.js:212:7
>>     at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
>>     at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
>>     at requireModule (/home/john/kb2/lib/require.js:226:3)
>>     at requireInternal (/home/john/kb2/lib/require.js:278:3)
>>     at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
>>     at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)
>>
>> /home/john/kb2/bin/kbox.js:116
>>       throw err;
>>             ^
>> kalabox-plugin-drush -> Cannot call method 'add' of undefined
>> TypeError: Cannot call method 'add' of undefined
>>     at /home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:168:16
>>     at EventEngine.on (/home/john/kb2/lib/core/events.js:59:5)
>>     at Object.exports.on (/home/john/kb2/lib/core/events.js:158:17)
>>     at Object.exports.whenApp (/home/john/kb2/lib/kbox.js:43:15)
>>     at Function.module.exports (/home/john/kalabox/apps/blog/node_modules/kalabox-plugin-drush/index.js:18:8)
>>     at Object.exports.call (/home/john/kb2/lib/core/deps.js:215:13)
>>     at /home/john/kb2/lib/require.js:349:39
>>     at /home/john/kb2/lib/require.js:229:7
>>     at requireFromOtherDirs (/home/john/kb2/lib/require.js:164:3)
>>     at /home/john/kb2/lib/require.js:212:7
>>     at requireFromNodeModules (/home/john/kb2/lib/require.js:125:3)
>>     at requireFromNodeModulesAndOtherDirs (/home/john/kb2/lib/require.js:200:3)
>>     at requireModule (/home/john/kb2/lib/require.js:226:3)
>>     at requireInternal (/home/john/kb2/lib/require.js:278:3)
>>     at Object.exports.require (/home/john/kb2/lib/require.js:433:5)
>>     at Object.exports.require (/home/john/kb2/lib/kbox.js:39:12)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox-issues/issues/382>.
>>
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
>

-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Here is my package.json for the app:

```
{
  "name": "kalabox-app-blog",
  "version": "0.0.0",
  "description": "A simple Drupal7 app",
  "license": "MIT License",
  "dependencies": {
    "kalabox-plugin-dbenv": "~0.5.1",
    "kalabox-plugin-drush": "~0.5.1",
    "kalabox-plugin-git": "~0.5.1",
    "kalabox-plugin-rsync": "~0.5.1"
  }
}
```

**Comment by pirog** [comment]
Should work. Do the versions of those plugins match up with what is in your
nose modules folder?

On Tuesday, April 7, 2015, John Ouellet <notifications@github.com> wrote:

> Here is my package.json for the app:
>
> {
>   "name": "kalabox-app-blog",
>   "version": "0.0.0",
>   "description": "A simple Drupal7 app",
>   "license": "MIT License",
>   "dependencies": {
>     "kalabox-plugin-dbenv": "~0.5.1",
>     "kalabox-plugin-drush": "~0.5.1",
>     "kalabox-plugin-git": "~0.5.1",
>     "kalabox-plugin-rsync": "~0.5.1"
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/382#issuecomment-90768920>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Well I have to build the app from scratch again, but I will do that tomorrow.  the plugins I copied from another app were all 0.5.1.

This app did try to install these versions with that package.json:
```
kalabox-plugin-dbenv@0.5.1 node_modules/kalabox-plugin-dbenv

kalabox-plugin-rsync@0.5.2 node_modules/kalabox-plugin-rsync

kalabox-plugin-git@0.6.0 node_modules/kalabox-plugin-git

kalabox-plugin-drush@0.5.2 node_modules/kalabox-plugin-drush
```

**Comment by pirog** [comment]
You can see that it tries to install 0.6.0 for the git plugin. Hence the
fail. You don't need to rebuild the entire app just its node dependencies.

On Tuesday, April 7, 2015, John Ouellet <notifications@github.com> wrote:

> Well I have to build the app from scratch again, but I will do that
> tomorrow. the plugins I copied from another app were all 0.5.1.
>
> This app did try to install these versions with that package.json:
>
> kalabox-plugin-dbenv@0.5.1 node_modules/kalabox-plugin-dbenv
>
> kalabox-plugin-rsync@0.5.2 node_modules/kalabox-plugin-rsync
>
> kalabox-plugin-git@0.6.0 node_modules/kalabox-plugin-git
>
> kalabox-plugin-drush@0.5.2 node_modules/kalabox-plugin-drush
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/382#issuecomment-90769584>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
Yes I see that, but I am just posting what it does.  I will try and win in the AM and report back.

**Comment by labboy0276** [comment]
Hello Again

so, doing this fixed it in my package.json:

```
{
  "name": "kalabox-app-msdw",
  "version": "0.0.0",
  "description": "A simple Drupal7 app",
  "license": "MIT License",
  "dependencies": {
    "kalabox-plugin-dbenv": "0.5.1",
    "kalabox-plugin-drush": "0.5.1",
    "kalabox-plugin-git": "0.5.1",
    "kalabox-plugin-rsync": "0.5.1"
  }
}
```

If the drush or git plugins are 0.5.2 or higher, what transpired int he first message keeps happening.

Thoughts?

**Comment by pirog** [comment]
There are Is no versions 0.5.2 so it's grabbing 0.6.0

On Wednesday, April 8, 2015, John Ouellet <notifications@github.com> wrote:

> Hello Again
>
> so, doing this fixed it in my package.json:
>
> {
>   "name": "kalabox-app-msdw",
>   "version": "0.0.0",
>   "description": "A simple Drupal7 app",
>   "license": "MIT License",
>   "dependencies": {
>     "kalabox-plugin-dbenv": "0.5.1",
>     "kalabox-plugin-drush": "0.5.1",
>     "kalabox-plugin-git": "0.5.1",
>     "kalabox-plugin-rsync": "0.5.1"
>   }
> }
>
> If the drush or git plugins are 0.5.2 or higher, what transpired int he
> first message keeps happening.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/382#issuecomment-90925800>
> .
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
does ~0.5.1 work or just 0.5.1?

On Wed, Apr 8, 2015 at 8:39 AM, Mike Pirog <mike@kalamuna.com> wrote:

> There are Is no versions 0.5.2 so it's grabbing 0.6.0
>
>
> On Wednesday, April 8, 2015, John Ouellet <notifications@github.com>
> wrote:
>
>> Hello Again
>>
>> so, doing this fixed it in my package.json:
>>
>> {
>>   "name": "kalabox-app-msdw",
>>   "version": "0.0.0",
>>   "description": "A simple Drupal7 app",
>>   "license": "MIT License",
>>   "dependencies": {
>>     "kalabox-plugin-dbenv": "0.5.1",
>>     "kalabox-plugin-drush": "0.5.1",
>>     "kalabox-plugin-git": "0.5.1",
>>     "kalabox-plugin-rsync": "0.5.1"
>>   }
>> }
>>
>> If the drush or git plugins are 0.5.2 or higher, what transpired int he
>> first message keeps happening.
>>
>> Thoughts?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kalabox/kalabox-issues/issues/382#issuecomment-90925800>
>> .
>>
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
just 0.5.1.

**Comment by pirog** [comment]
~0.5.1 grabs 0.6.0?

On Wed, Apr 8, 2015 at 10:22 AM, John Ouellet <notifications@github.com>
wrote:

> just 0.5.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/382#issuecomment-90980158>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
correct

**Comment by pirog** [comment]
So i just tested this out using kalabox 0.5.2, the most recent kalabox-app=examples and the hiphop app example.

```
cd ~/Desktop/kalabox-app-examples
git checkout master && git pull
rm -rf node_modules
npm install
npm WARN package.json kalabox-app-hiphop-drupal7@0.0.0 No repository field.
kalabox-plugin-dbenv@0.5.1 node_modules/kalabox-plugin-dbenv

kalabox-plugin-rsync@0.5.2 node_modules/kalabox-plugin-rsync

kalabox-plugin-git@0.5.2 node_modules/kalabox-plugin-git

kalabox-plugin-drush@0.5.2 node_modules/kalabox-plugin-drush
└── lodash@2.4.1
```

works as expected.

**Comment by labboy0276** [comment]
strange, i will do more testings

**Comment by labboy0276** [comment]
I know what I did wrong, I forgot to remove my old node_modules when I upgraded the app.

Closing this out.
