### ISSUE TITLE
Duplicate App.Name when I run kbox apps

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#392]
As the title seyz, I run this:

```
john@kalamuna:~/kalabox/apps/k2g$ kbox apps
{ app: 'blog', running: 0, total: 0 }
{ app: 'csi-america', running: 0, total: 0 }
{ app: 'fiksu', running: 0, total: 0 }
{ app: 'k2g', running: 2, total: 3 }
{ app: 'k2g', running: 2, total: 3 }
{ app: 'kettering', running: 0, total: 0 }
{ app: 'kfp', running: 0, total: 0 }
{ app: 'msdw', running: 0, total: 0 }
{ app: 'rpool', running: 0, total: 0 }
```
The only app I have installed is k2g, the rest I havent re installed yet obviously.

appRegistry.json says:
{"appDirs":["/home/john/kalabox/apps/k2g"]}

I be on Ubuntu 12.04 if that matters

**Comment by bcauldwell** [comment]
@labboy0276 is this still happening? I had a hunch it might be just two kalabox.json app files with the same .appName value. Can you confirm that is not happening?

**Comment by labboy0276** [comment]
Hello!

it still happens to all my apps:

```
{ app: 'blog', running: 0, total: 0 }
{ app: 'csi-america', running: 0, total: 0 }
{ app: 'fiksu', running: 0, total: 0 }
{ app: 'k2g', running: 0, total: 3 }
{ app: 'k2g', running: 0, total: 3 }
{ app: 'kettering', running: 0, total: 3 }
{ app: 'kettering', running: 0, total: 3 }
{ app: 'kfp', running: 0, total: 0 }
{ app: 'msdw', running: 0, total: 0 }
{ app: 'peel', running: 2, total: 3 }
{ app: 'peel', running: 2, total: 3 }
{ app: 'prna', running: 0, total: 3 }
{ app: 'prna', running: 0, total: 3 }
{ app: 'rpool', running: 0, total: 0 }
{ app: 'ucsfp', running: 0, total: 0 }
{ app: 'ucsfp', running: 0, total: 0 }
```

**Comment by labboy0276** [comment]
the ones that dont have a double app are apps that are not installed yet.  They are just apps sitting in my kalabox/apps folder.

**Comment by pirog** [comment]
I just happenstance replicated this. It seems the diff might be apps that are stored in the appsRoot as opposed to otherwise.

**Comment by pirog** [comment]
followup: they only duplicate after you've installed/started

**Comment by bcauldwell** [comment]
I've pushed a fix for this. The app discovery algo was looking for apps in home/kalabox/apps and concat'ing with registered app, so once an app was both in home/kalabox/apps and registered it showed up twice. This was fixed by no longer discovering apps in home/kalabox/apps and instead relying on apps being registered during app install.
