### ISSUE TITLE
KBOX fails when restarting the engine on update

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#400]
Hello again

So, I installed kbox via git and a couple things happen on kbox provision that need a little TLC:

1. if kbox up is not run before the provision, this happens everytime on step 18:
```
{"level":"error","message":"code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n Error: code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n\n    at /home/john/kb2/lib/util/shell.js:60:13\n    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7\n    at ChildProcess.exithandler (child_process.js:662:7)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:766:16)\n    at Socket.<anonymous> (child_process.js:979:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:466:12)","timestamp":"2015-04-16T14:41:36.558Z"}
```
That is the output in the error log itself.

2. Since I rock the Ubuntu I need to clear out my resolvconf and restart the service before I do the provision otherwise it takes hours to win.

**Comment by pirog** [comment]
What version are you on?

On Thursday, April 16, 2015, John Ouellet <notifications@github.com> wrote:

> Hello again
>
> So, I installed kbox via git and a couple things happen on kbox provision
> that need a little TLC:
>
>    1. if kbox up is not run before the provision, this happens everytime
>    on step 18:
>
> {"level":"error","message":"code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n Error: code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n\n    at /home/john/kb2/lib/util/shell.js:60:13\n    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7\n    at ChildProcess.exithandler (child_process.js:662:7)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:766:16)\n    at Socket.<anonymous> (child_process.js:979:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:466:12)","timestamp":"2015-04-16T14:41:36.558Z"}
>
> That is the output in the error log itself.
>
>    1. Since I rock the Ubuntu I need to clear out my resolvconf and
>    restart the service before I do the provision otherwise it takes hours to
>    win.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/400>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by pirog** [comment]
I also assume you are talking about the update provision not the initial
provision? What step is step 18? These are OS specific.

On Thursday, April 16, 2015, John Ouellet <notifications@github.com> wrote:

> Hello again
>
> So, I installed kbox via git and a couple things happen on kbox provision
> that need a little TLC:
>
>    1. if kbox up is not run before the provision, this happens everytime
>    on step 18:
>
> {"level":"error","message":"code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n Error: code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n\n    at /home/john/kb2/lib/util/shell.js:60:13\n    at /home/john/kb2/node_modules/shelljs/src/exec.js:107:7\n    at ChildProcess.exithandler (child_process.js:662:7)\n    at ChildProcess.emit (events.js:98:17)\n    at maybeClose (child_process.js:766:16)\n    at Socket.<anonymous> (child_process.js:979:11)\n    at Socket.emit (events.js:95:17)\n    at Pipe.close (net.js:466:12)","timestamp":"2015-04-16T14:41:36.558Z"}
>
> That is the output in the error log itself.
>
>    1. Since I rock the Ubuntu I need to clear out my resolvconf and
>    restart the service before I do the provision otherwise it takes hours to
>    win.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/400>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
"version": "0.6.6"

not the initial provision, the update.

info: -- Step 18/20 --
info: Restarting engine for updates...


On Thu, Apr 16, 2015 at 11:15 AM, Mike Pirog <notifications@github.com>
wrote:

> I also assume you are talking about the update provision not the initial
> provision? What step is step 18? These are OS specific.
>
>
> On Thursday, April 16, 2015, John Ouellet <notifications@github.com>
> wrote:
>
> > Hello again
> >
> > So, I installed kbox via git and a couple things happen on kbox provision
> > that need a little TLC:
> >
> > 1. if kbox up is not run before the provision, this happens everytime
> > on step 18:
> >
> > {"level":"error","message":"code: 1, msg: error in run: Failed to start
> machine \"Kalabox2\": Failed to start%!(EXTRA string=Kalabox2)\n Error:
> code: 1, msg: error in run: Failed to start machine \"Kalabox2\": Failed to
> start%!(EXTRA string=Kalabox2)\n\n at
> /home/john/kb2/lib/util/shell.js:60:13\n at
> /home/john/kb2/node_modules/shelljs/src/exec.js:107:7\n at
> ChildProcess.exithandler (child_process.js:662:7)\n at ChildProcess.emit
> (events.js:98:17)\n at maybeClose (child_process.js:766:16)\n at
> Socket.<anonymous> (child_process.js:979:11)\n at Socket.emit
> (events.js:95:17)\n at Pipe.close
> (net.js:466:12)","timestamp":"2015-04-16T14:41:36.558Z"}
> >
> > That is the output in the error log itself.
> >
> > 1. Since I rock the Ubuntu I need to clear out my resolvconf and
> > restart the service before I do the provision otherwise it takes hours to
> > win.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/kalabox/kalabox-issues/issues/400>.
> >
>
>
> --
> Cheers,
>
> Mike Pirog
> Kalamuna
> www.kalamuna.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/400#issuecomment-93760458>
> .
>



-- 
*John Ouellet*
*Developer & Support Manager*
415-470-3076
www.kalamuna.com

**Comment by pirog** [comment]
k, ill try to replicate.

also #386 already exists for the DNS issue on update on nix

**Comment by pirog** [comment]
I can't replicate this on OSX with developer install on 0.6.6
