### ISSUE TITLE
IMPROVEMENT: Error message on kbox uninstall "Cannot remove the container [HASH] it does NOT exist!" should return container name

### ISSUE THREAD

**Issue by reynoldsalec** [kalabox/kalabox-issues#415]
While doing a couple kbox uninstall/install combos in testing a plugin, I got into a strange situation where kbox uninstall would relay something like the following:

```
Cannot remove the container "3b29e85b5f06f48f68a9e51dff1eff740c1ef1fab1262fab4f9fdb26c1a3ac70" it does NOT exist!
```

It would be more helpful to state the container name, instead of the hash.

**Comment by bcauldwell** [comment]
I agree. I'd like to take a look at this over the weekend or Monday
morning. lib/app.js is some of the oldest code we have and the hash stuff
is left over from prehistoric times and deserves some TLC.

On Fri, Apr 24, 2015 at 6:03 PM, reynoldsalec <notifications@github.com>
wrote:

> While doing a couple kbox uninstall/install combos in testing a plugin, I
> got into a strange situation where kbox uninstall would relay something
> like the following:
>
> Cannot remove the container "3b29e85b5f06f48f68a9e51dff1eff740c1ef1fab1262fab4f9fdb26c1a3ac70" it does NOT exist!
>
> It would be more helpful to state the container name, instead of the hash.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/415>.
>



-- 
- Benjamin Cauldwell

**Comment by pirog** [comment]
This issue was moved to kalabox/kalabox#237
