### ISSUE TITLE
Error while shutting down. code: 1, msg: error in run: Failed to stop machine "Kalabox2": exit status 1

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#416]
I saw this message as the person in #341 commented on.

I have been getting this message since upgrading to 0.6.0.  I am not sure if it is related to #341 but I thought I would open a separate ticket just in case.

```
john@kalamuna:~/kalabox/apps/peel/code$ kbox down
info: B2D => Shutting down.
info: B2D => Error while shutting down. code: 1, msg: error in run: Failed to stop machine "Kalabox2": exit status 1

john@kalamuna:~/kalabox/apps/peel/code$ kbox down
info: B2D => Shutting down.
Kalabox engine has been deactivated.
info: B2D => Shut down.
```

**Comment by pirog** [comment]
yeah this seems to happen periodically for me as well. its not really an error as the VM does shut down... not sure if this is maybe a false reporting by VB or B2D.

**Comment by bcauldwell** [comment]
Fixed by wrapping in a retry with maxRetries of 3.
