### ISSUE TITLE
uninstall-linux.sh: line 27: VMs/Kalabox2: No such file or directory

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#435]
When running uninstall script:

I see this in the list:

```
uninstall-linux.sh: line 27: VMs/Kalabox2: No such file or directory
```

**Comment by pirog** [comment]
So this line just removes the actual VM files but it might be different on
debian... if you can find out where these things live and submit a PR it
would be grand.

On Thu, May 7, 2015 at 12:32 PM, John Ouellet <notifications@github.com>
wrote:

> When running uninstall script:
>
> I see this in the list:
>
> uninstall-linux.sh: line 27: VMs/Kalabox2: No such file or directory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/435>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com
