### ISSUE TITLE
REFACTOR: A restart of an app takes way too long, something should be done to speed that process up.

### ISSUE THREAD

**Issue by bcauldwell** [kalabox/kalabox-issues#453]
1) - Having to restart an app for something like some nodejs server side code changes to take effect can be a pain. If we could get around always restarting syncthing for a restart we can make it a much faster process.

2) - Being able to just restart a single component would be nice. Something like 'kbox restart <componentName>' would be very helpful and fast.

**Comment by pirog** [comment]
Going to close this in favor of a new issue with our discussions about putting the syncthing index inside a volume
