### ISSUE TITLE
Kalabox died on me after my puter crashed mid stroke

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#462]
Pretty much like the title says, KB2 said no.  I was winning in many levels yesterday and my computer froze up for some reason or another while doing heavy lifting.  I went back in and tried to get back to where I was.  I got this:

```
john@kalamuna:~/kalabox$ kbox up
info: B2D => Starting up...
Kalabox engine has been activated.
info: B2D => Started up.
john@kalamuna:~/kalabox$ cd apps/son
john@kalamuna:~/kalabox/apps/son$ kbox start
undefined
john@kalamuna:~/kalabox/apps/son$ kbox rebuild
undefined
john@kalamuna:~/kalabox/apps/son$ kbox down
info: B2D => Shutting down.
Kalabox engine has been deactivated.
info: B2D => Shut down.
john@kalamuna:~/kalabox/apps/son$ kbox up
info: B2D => Starting up...
Kalabox engine has been activated.
info: B2D => Started up.
john@kalamuna:~/kalabox/apps/son$ kbox start
undefined
```

I cried a little since this was strange.  I ssh'd inro the kb2 b2d and all my containers were there, everything seemed kosher.  It just wouldn't win.

So I said otay, I will just re-provision.  I pulled down the latest kb2 and ran kbox provision only to get this every time:

```
info: -- Step 15/19 --
info: Preparing apps for updates...
info: -- OK! 79% complete! --

connect ECONNREFUSED
```

Finally, I just uninstalled and re-installed.  Now it works fine.  I have to repull all my DBs and files, but whatevs.  I am in Ubuntu 12.04 as you know and this is probably just an isolated oddness, but I thought I would report it.

**Comment by pirog** [comment]
Thanks for reporting this. Did you happen to save any of the logs from when this happened?

**Comment by labboy0276** [comment]
I uninstalled KB2 with the script, not sure if i keeps the logs?

**Comment by pirog** [comment]
they are in `~/.kalabox/logs` if you want to check

On Tue, Jun 2, 2015 at 3:15 PM, John Ouellet <notifications@github.com>
wrote:

> I uninstalled KB2 with the script, not sure if i keeps the logs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalabox/kalabox-issues/issues/462#issuecomment-108114341>
> .
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by labboy0276** [comment]
File was too big for gist:

http://www.jazzyballz.com/sites/default/files/kb2-logs.txt

That was today's log
