### ISSUE TITLE
Windows: Drupal app available by IP, but not by host name

### ISSUE THREAD

**Issue by UTANdev** [kalabox/kalabox-issues#470]
On my Windows 7 box, I created and started a Drupal app named mtms. `kbox ip` returns 10.13.37.42. According to the docs, I should be able to connect to the database at the hostname mtms.kbox. This fails, but connecting to the database at 10.13.37.42 works.

Does Kalabox not create a host entry on Windows?

**Comment by pirog** [comment]
you should be able to do that but you need to get the correct port by running `kbox containers` inside of your app and finding what port number forwards to 3306.

Can you access your site at `mtms.kbox` in the browser?

**Comment by pirog** [comment]
Sorry... actually should clarify first. From where are you trying to connect to the DB?

**Comment by UTANdev** [comment]
When I'm inside the app folder, `kbox containers` returns:

```json
{
  "id": "803d2a16e759069b55a1dcdd7d4109d057f7d7377878ffa95a8fde6d82f88317",
  "name": "kb_mtms_db",
  "app": "mtms",
  "ports": [
    "3306/tcp=>32770"
  ],
  "running": true
}
{
  "id": "4169cdaeb00473c338ba0f0b4220260c943f7f5ae5c9f0a1d48ca823f8234329",
  "name": "kb_mtms_appserver",
  "app": "mtms",
  "ports": [
    "443/tcp=>32768",
    "80/tcp=>32769"
  ],
  "running": true
}
```
I was trying to connect using a GUI, HeidiSQL. As for Web access, DNS lookup fails when I point my browser to http://mtms.kbox .

**Comment by pirog** [comment]
Can you go into your network settings and paste in the config for your two Virtual Box Host-Only adapters?

**Comment by UTANdev** [comment]
```
Ethernet adapter VirtualBox Host-Only Network:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
   Physical Address. . . . . . . . . : 08-00-27-00-4C-C9
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::3420:71a4:68b8:626b%16(Preferred) 
   IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 
   DHCPv6 IAID . . . . . . . . . . . : 285736999
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-14-D0-EF-AD-F0-4D-A2-3A-8B-E0
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter #2
   Physical Address. . . . . . . . . : 08-00-27-00-6C-49
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::fd89:f8ab:b844:b2ed%18(Preferred) 
   IPv4 Address. . . . . . . . . . . : 10.13.37.1(Preferred) 
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 
   DHCPv6 IAID . . . . . . . . . . . : 453509159
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-14-D0-EF-AD-F0-4D-A2-3A-8B-E0
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{31CEC7BE-E34D-490F-AD90-409B4B683CE9}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Local Area Connection* 9:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . : 
   Description . . . . . . . . . . . : Microsoft 6to4 Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
```

**Comment by pirog** [comment]
Got it. So it looks like maybe the provision didnt add in the correct DNS servers. What you will want to do is add the following servers to the `Ethernet adapter VirtualBox Host-Only Network #2`:

```
10.13.37.42
10.13.37.43
```

You may have to refresh your DNS after this. I would try this and see if it resolves your issue.

**Comment by UTANdev** [comment]
My PC restarted overnight (Windows update). I restarted kalabox and my mtms app and I can actually access http://mtms.kbox without any configuration changes. Woo! So let's chalk this up to a fluke for now.

I'm *so* excited to be working with this nimble, state-of-the-art development environment! Thanks for bringing it to us.

**Comment by pirog** [comment]
config looks the same so not sure exactly what changed... maybe just needed a DNS refresh and the reboot did that. Glad this seemed to work though!

**Comment by UTANdev** [comment]
Sorry, no. I forgot that, the day before, I'd hardcoded a DNS entry in my Windows hosts file.

I removed that manual entry, made the changes you suggested to the VirtualBox Host-Only Ethernet Adapter #2, rebooted and restarted both kalabox and my mtms app. The result: although the DNS servers do appear in the networking adapter's settings, http://mtms.kbox is still unreachable.

What next? Thanks.

**Comment by pirog** [comment]
So... it worked before because you had edited the hosts file? What was the entry you put in there?

**Comment by UTANdev** [comment]
10.13.37.42       mtms.kbox

**Comment by pirog** [comment]
Got it. So all the apps actually run behind a reverse proxy called hipache so port 80 on 10.13.37.42 is actually hipache. What hipache does is route mtms.kbox to some other port on 10.13.37.42 where your website is. 

You can find this port by running kbox containers inside your app directory after you've started your app.

**Comment by UTANdev** [comment]
Well, it works fine without the manual hosts entry; I can access mtms.kbox in my web browser, so let's consider this issue closed. Thanks for your help, Mike.

**Comment by pirog** [comment]
closed issues are the best issues
