### ISSUE TITLE
Possibly ask for VM size on initial provision?

### ISSUE THREAD

**Issue by labboy0276** [kalabox/kalabox-issues#474]
I just had to redo all my kb2 because I ran out of room.  I forgot to run the d flag the first time I provisioned a couple weeks ago.

Looks like you cant re run the kbox provision -- -d when you already have it created.  Do you think we could ask for this on initial install?  Is that possible?

**Comment by pirog** [comment]
I feel like -d is better suited as an option than something for which you are prompted. that said it would be great to just have the underlying virtual storage increase automatically.

**Comment by labboy0276** [comment]
that would be the most goodest option as well.
